"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { useCreateRun } from "@/lib/query/runs";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { MessageSquare, Zap } from "lucide-react";
import { toast } from "sonner";

const CREATOR_PLACEHOLDER = `e.g. @fitnessbysarah — 280k TikTok followers, strength training & nutrition content. Posts 5x/week. Audience: 18-35 women. High engagement on transformation posts. Recent viral video on progressive overload basics.`;

const BRAND_PLACEHOLDER = `e.g. NutriPeak — premium protein powder brand targeting active women. Key differentiator: clean label, no artificial sweeteners. Looking for authentic fitness creators who actually use protein supplements in their training routine.`;

export default function OutreachPage() {
  const [creatorProfile, setCreatorProfile] = useState("");
  const [brandContext, setBrandContext] = useState("");
  const router = useRouter();
  const { mutate: createRun, isPending } = useCreateRun();

  function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!creatorProfile.trim() || !brandContext.trim()) return;

    createRun(
      {
        tool_type: "outreach",
        input: {
          creatorProfile: creatorProfile.trim(),
          brandContext: brandContext.trim(),
        },
      },
      {
        onSuccess: ({ runId }) => {
          router.push(`/tools/outreach/${runId}`);
        },
        onError: (err) => {
          toast.error(err.message ?? "Failed to start outreach run");
        },
      }
    );
  }

  const canSubmit =
    creatorProfile.trim().length >= 20 && brandContext.trim().length >= 20;

  return (
    <div className="max-w-2xl mx-auto px-4 py-16">
      <div className="text-center mb-10">
        <Badge variant="secondary" className="mb-4">
          Structured LLM output
        </Badge>
        <h1 className="text-3xl font-bold tracking-tight mb-3">
          Outreach Drafter
        </h1>
        <p className="text-muted-foreground text-lg">
          Describe a creator and your brand. Get three personalized DM drafts in
          different tones — Friendly, Direct, and Witty.
        </p>
      </div>

      <form onSubmit={handleSubmit} className="space-y-6">
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-base">
              <MessageSquare className="h-4 w-4" />
              Creator Profile
            </CardTitle>
            <CardDescription>
              Describe the creator: handle, platform, niche, audience, content style (20–2000 chars)
            </CardDescription>
          </CardHeader>
          <CardContent>
            <Textarea
              value={creatorProfile}
              onChange={(e) => setCreatorProfile(e.target.value)}
              placeholder={CREATOR_PLACEHOLDER}
              rows={4}
              disabled={isPending}
              className="resize-none"
            />
            <p className="text-xs text-muted-foreground mt-2 text-right">
              {creatorProfile.length} / 2000
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-base">
              <Zap className="h-4 w-4" />
              Brand Context
            </CardTitle>
            <CardDescription>
              Describe your brand: name, product, differentiator, why this creator fits (20–2000 chars)
            </CardDescription>
          </CardHeader>
          <CardContent>
            <Textarea
              value={brandContext}
              onChange={(e) => setBrandContext(e.target.value)}
              placeholder={BRAND_PLACEHOLDER}
              rows={4}
              disabled={isPending}
              className="resize-none"
            />
            <p className="text-xs text-muted-foreground mt-2 text-right">
              {brandContext.length} / 2000
            </p>
          </CardContent>
        </Card>

        <Button
          type="submit"
          disabled={isPending || !canSubmit}
          className="w-full"
          size="lg"
        >
          {isPending ? (
            <>
              <Zap className="h-4 w-4 mr-2 animate-pulse" />
              Generating drafts...
            </>
          ) : (
            <>
              <Zap className="h-4 w-4 mr-2" />
              Generate Outreach Drafts
            </>
          )}
        </Button>
      </form>

      <p className="text-center text-xs text-muted-foreground mt-8">
        Drafts are generated by Claude with structured output. Each is 80–150 words,
        tailored to the creator&apos;s content style and brand fit.
      </p>
    </div>
  );
}
